import re
import logging
from typing import Set
import bleach
from bs4 import BeautifulSoup

logger = logging.getLogger("lenny.security")

# Allowed HTML tags for rendered artifacts
ALLOWED_TAGS: Set[str] = {
    "a", "abbr", "acronym", "b", "blockquote", "br", "code", "em", "i", "li", "ol",
    "p", "strong", "ul", "h1", "h2", "h3", "h4", "h5", "h6", "hr", "pre", "div",
    "span", "table", "thead", "tbody", "tfoot", "tr", "th", "td", "caption",
    "section", "article", "header", "footer", "main", "aside", "nav", "figure",
    "figcaption", "mark", "small", "sub", "sup", "del", "ins", "details", "summary",
    "img", "svg", "path", "circle", "rect", "line", "polyline", "polygon", "style"
}

# Allowed HTML attributes
ALLOWED_ATTRIBUTES = {
    "*": ["class", "id", "style", "title", "aria-*", "role"],
    "a": ["href", "title", "target", "rel"],
    "img": ["src", "alt", "title", "width", "height", "loading"],
    "svg": ["viewbox", "width", "height", "fill", "stroke", "xmlns", "version"],
    "path": ["d", "fill", "stroke", "stroke-width", "stroke-linecap", "stroke-linejoin"],
    "circle": ["cx", "cy", "r", "fill", "stroke"],
    "rect": ["x", "y", "width", "height", "rx", "ry", "fill", "stroke"],
    "th": ["scope", "colspan", "rowspan", "align"],
    "td": ["colspan", "rowspan", "align"],
}

# Allowed URL protocols
ALLOWED_PROTOCOLS = ["http", "https", "mailto", "#"]

# Allowed CSS properties: intentionally narrow to the CSS used by safe artifact cards/layouts.
# This preserves HTML sanitization while blocking dangerous CSS features and XSS vectors.
ALLOWED_CSS_PROPERTIES = [
    "color",
    "background-color",
    "padding",
    "padding-top",
    "padding-right",
    "padding-bottom",
    "padding-left",
    "border-radius",
    "border",
    "border-color",
    "border-width",
    "border-style",
    "font-family",
    "font-size",
    "font-weight",
    "text-align",
    "line-height",
    "margin",
    "margin-top",
    "margin-bottom",
    "margin-left",
    "margin-right",
    "width",
    "height",
    "max-width",
    "min-width",
    "display",
    "justify-content",
    "align-items",
    "gap",
    "overflow",
    "overflow-x",
    "overflow-y",
    "position",
    "top",
    "left",
    "right",
    "bottom",
    "z-index",
    "opacity",
]

# Configure CSS sanitizer if available. `tinycss2` is required for Bleach CSS sanitization.
css_sanitizer = None
try:
    from bleach.css_sanitizer import CSSSanitizer
    css_sanitizer = CSSSanitizer(allowed_css_properties=ALLOWED_CSS_PROPERTIES)
except Exception as e:
    logger.warning("Could not initialize bleach CSSSanitizer: %s", e)


def sanitize_html(raw_html: str) -> str:
    """
    Sanitizes untrusted HTML generated by LLM models before saving or rendering.
    
    Guarantees:
    - All <script>, <object>, <embed>, <iframe> elements are completely stripped.
    - All inline event handlers ('onclick', 'onload', 'onerror', etc.) are stripped.
    - URL schemes are restricted strictly to http, https, mailto, and relative hashes (#).
    - Prevents parent document access and Cross-Site Scripting (XSS).
    """
    if not raw_html or not raw_html.strip():
        return ""

    try:
        import html
        # Pre-process: parse with BeautifulSoup to strip high-risk elements and handlers
        soup = BeautifulSoup(raw_html, "html.parser")
        
        prohibited_tags = [
            "script", "iframe", "object", "embed", "applet", "meta", "base", "form",
            "animate", "set", "handler", "listener", "frame", "frameset"
        ]
        for tag_name in prohibited_tags:
            for el in soup.find_all(tag_name):
                el.decompose()

        # Remove any on* event handler attributes and dangerous schemes across all tags
        for tag in soup.find_all(True):
            attrs = dict(tag.attrs)
            for attr, val in attrs.items():
                attr_lower = attr.lower()
                # 1. Any on* or data-on* attribute (onclick, onload, onerror, onmouseover, etc.)
                if attr_lower.startswith("on") or attr_lower.startswith("data-on") or "onload" in attr_lower or "onerror" in attr_lower:
                    del tag.attrs[attr]
                    continue

                # 2. Check attribute value for dangerous protocols (including entity-encoded)
                val_str = str(val).strip()
                val_decoded = html.unescape(val_str).lower().replace(" ", "").replace("\t", "").replace("\n", "").replace("\r", "")
                if any(val_decoded.startswith(proto) for proto in ("javascript:", "data:text/html", "vbscript:")):
                    del tag.attrs[attr]

        cleaned_intermediate = str(soup)

        # Bleach clean with whitelist & css_sanitizer
        bleach_kwargs = {
            "tags": ALLOWED_TAGS,
            "attributes": ALLOWED_ATTRIBUTES,
            "protocols": ALLOWED_PROTOCOLS,
            "strip": True
        }
        if css_sanitizer:
            bleach_kwargs["css_sanitizer"] = css_sanitizer

        cleaned_html = bleach.clean(cleaned_intermediate, **bleach_kwargs)

        # Sanitize style blocks: defang url(), @import, expression(), behavior:, -moz-binding
        cleaned_html = re.sub(r'url\s*\([^)]*javascript:[^)]*\)', 'none', cleaned_html, flags=re.IGNORECASE)
        cleaned_html = re.sub(r'url\s*\([^)]*data:[^)]*\)', 'none', cleaned_html, flags=re.IGNORECASE)
        cleaned_html = re.sub(r'url\s*\((?![\'"]?(?:https?:|data:image\/))', 'blocked-url(', cleaned_html, flags=re.IGNORECASE)
        cleaned_html = re.sub(r'@import\b[^;]*;?', '/* blocked-import */', cleaned_html, flags=re.IGNORECASE)
        cleaned_html = re.sub(r'expression\s*\([^;}]*', 'inherit', cleaned_html, flags=re.IGNORECASE)
        cleaned_html = re.sub(r'behavior\s*:[^;]*;?', '', cleaned_html, flags=re.IGNORECASE)
        cleaned_html = re.sub(r'-moz-binding\s*:[^;]*;?', '', cleaned_html, flags=re.IGNORECASE)

        logger.debug("Successfully sanitized HTML (original len=%d, cleaned len=%d)", len(raw_html), len(cleaned_html))
        return cleaned_html

    except Exception as e:
        logger.error("Error sanitizing HTML content: %s", e)
        return bleach.clean(raw_html, tags=[], strip=True)
