import logging
from fastapi import APIRouter, Depends, HTTPException, status
from pydantic import BaseModel
from typing import Optional, List, Dict, Any
from sqlalchemy.ext.asyncio import AsyncSession

from app.db.database import get_db
from app.db.repositories import SessionRepository, MessageRepository, ArtifactRepository
from app.llm.base import LLMMessage
from app.llm.factory import get_llm_provider
from app.agents.core import LennyAgentEngine

logger = logging.getLogger("lenny.api.chat")
router = APIRouter(prefix="/api/chat", tags=["Chat"])


class ChatRequest(BaseModel):
    session_id: str
    message: str
    provider: Optional[str] = None
    model: Optional[str] = None


class ArtifactPayload(BaseModel):
    id: str
    session_id: str
    title: str
    type: str
    content: str
    sanitized_content: Optional[str] = None


class ChatResponse(BaseModel):
    message_id: str
    session_id: str
    role: str = "assistant"
    content: str
    intent: str
    sources: List[Dict[str, Any]] = []
    artifact: Optional[ArtifactPayload] = None
    provider: str
    model: str
    tool_calls: List[str] = []
    evidence_sufficient: bool = True


@router.post("", response_model=ChatResponse)
async def chat_endpoint(
    payload: ChatRequest,
    db: AsyncSession = Depends(get_db)
):
    session_repo = SessionRepository(db)
    msg_repo = MessageRepository(db)
    art_repo = ArtifactRepository(db)

    # 1. Verify session exists or auto-create
    session = await session_repo.get_session(payload.session_id)
    if not session:
        session = await session_repo.create_session(
            title=payload.message[:45] + ("..." if len(payload.message) > 45 else "")
        )

    # 2. Save incoming user message
    await msg_repo.add_message(
        session_id=session.id,
        role="user",
        content=payload.message
    )

    # Update session title if first exchange
    if session.title == "New Conversation":
        new_title = payload.message.strip().split("\n")[0][:45]
        if len(payload.message) > 45:
            new_title += "..."
        await session_repo.update_session_title(session.id, new_title)

    # 3. Retrieve conversation history for context
    past_messages = await msg_repo.get_session_messages(session.id, limit=10)
    history_messages = [
        LLMMessage(role=m.role, content=m.content)
        for m in past_messages[:-1]
    ]

    # 4. Resolve LLM provider
    llm_provider = get_llm_provider(
        provider_override=payload.provider,
        model_override=payload.model
    )

    # 5. Execute unified Agent Engine (Anthropic Claude Agent SDK in Cloud / Tool dispatch in Local)
    agent_engine = LennyAgentEngine(llm_provider)

    try:
        agent_result = await agent_engine.run(
            user_message=payload.message,
            conversation_history=history_messages
        )
    except Exception as e:
        logger.exception("Agent execution failed: %s", e)
        raise HTTPException(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
            detail=f"Agent execution failed: {str(e)}"
        )

    # 6. Save artifact if generated by tool
    artifact_payload = None
    if agent_result.artifact:
        created_artifact = await art_repo.create_artifact(
            session_id=session.id,
            type=agent_result.artifact["type"],
            title=agent_result.artifact["title"],
            content=agent_result.artifact["content"],
            sanitized_content=agent_result.artifact.get("sanitized_content")
        )
        artifact_payload = ArtifactPayload(
            id=created_artifact.id,
            session_id=created_artifact.session_id,
            title=created_artifact.title,
            type=created_artifact.type,
            content=created_artifact.content,
            sanitized_content=created_artifact.sanitized_content
        )

    # 7. Save assistant message to DB
    saved_msg = await msg_repo.add_message(
        session_id=session.id,
        role="assistant",
        content=agent_result.content,
        sources=agent_result.sources,
        intent=agent_result.intent
    )

    return ChatResponse(
        message_id=saved_msg.id,
        session_id=session.id,
        content=agent_result.content,
        intent=agent_result.intent,
        sources=agent_result.sources,
        artifact=artifact_payload,
        provider=llm_provider.provider_name,
        model=llm_provider.model_name,
        tool_calls=agent_result.tool_calls,
        evidence_sufficient=agent_result.evidence_sufficient
    )
